---
- hosts: qaserver
  become: yes
  ignore_errors: yes
  tasks:
    - name: installing package
      package:
        name: "{{ item }}"
        state: present
    with_items:
      - unzip
      - wget
      - httpd
